# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alireza/PhDRepository/implementations/DIPOA/nonlinear_conjugate_gradient

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alireza/PhDRepository/implementations/DIPOA/nonlinear_conjugate_gradient

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alireza/PhDRepository/implementations/DIPOA/nonlinear_conjugate_gradient/CMakeFiles /home/alireza/PhDRepository/implementations/DIPOA/nonlinear_conjugate_gradient/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alireza/PhDRepository/implementations/DIPOA/nonlinear_conjugate_gradient/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nonlinear_conjugate_gradient

# Build rule for target.
nonlinear_conjugate_gradient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nonlinear_conjugate_gradient
.PHONY : nonlinear_conjugate_gradient

# fast build rule for target.
nonlinear_conjugate_gradient/fast:
	$(MAKE) -f CMakeFiles/nonlinear_conjugate_gradient.dir/build.make CMakeFiles/nonlinear_conjugate_gradient.dir/build
.PHONY : nonlinear_conjugate_gradient/fast

src/cg.o: src/cg.cpp.o

.PHONY : src/cg.o

# target to build an object file
src/cg.cpp.o:
	$(MAKE) -f CMakeFiles/nonlinear_conjugate_gradient.dir/build.make CMakeFiles/nonlinear_conjugate_gradient.dir/src/cg.cpp.o
.PHONY : src/cg.cpp.o

src/cg.i: src/cg.cpp.i

.PHONY : src/cg.i

# target to preprocess a source file
src/cg.cpp.i:
	$(MAKE) -f CMakeFiles/nonlinear_conjugate_gradient.dir/build.make CMakeFiles/nonlinear_conjugate_gradient.dir/src/cg.cpp.i
.PHONY : src/cg.cpp.i

src/cg.s: src/cg.cpp.s

.PHONY : src/cg.s

# target to generate assembly for a file
src/cg.cpp.s:
	$(MAKE) -f CMakeFiles/nonlinear_conjugate_gradient.dir/build.make CMakeFiles/nonlinear_conjugate_gradient.dir/src/cg.cpp.s
.PHONY : src/cg.cpp.s

src/line_search.o: src/line_search.cpp.o

.PHONY : src/line_search.o

# target to build an object file
src/line_search.cpp.o:
	$(MAKE) -f CMakeFiles/nonlinear_conjugate_gradient.dir/build.make CMakeFiles/nonlinear_conjugate_gradient.dir/src/line_search.cpp.o
.PHONY : src/line_search.cpp.o

src/line_search.i: src/line_search.cpp.i

.PHONY : src/line_search.i

# target to preprocess a source file
src/line_search.cpp.i:
	$(MAKE) -f CMakeFiles/nonlinear_conjugate_gradient.dir/build.make CMakeFiles/nonlinear_conjugate_gradient.dir/src/line_search.cpp.i
.PHONY : src/line_search.cpp.i

src/line_search.s: src/line_search.cpp.s

.PHONY : src/line_search.s

# target to generate assembly for a file
src/line_search.cpp.s:
	$(MAKE) -f CMakeFiles/nonlinear_conjugate_gradient.dir/build.make CMakeFiles/nonlinear_conjugate_gradient.dir/src/line_search.cpp.s
.PHONY : src/line_search.cpp.s

src/problem.o: src/problem.cpp.o

.PHONY : src/problem.o

# target to build an object file
src/problem.cpp.o:
	$(MAKE) -f CMakeFiles/nonlinear_conjugate_gradient.dir/build.make CMakeFiles/nonlinear_conjugate_gradient.dir/src/problem.cpp.o
.PHONY : src/problem.cpp.o

src/problem.i: src/problem.cpp.i

.PHONY : src/problem.i

# target to preprocess a source file
src/problem.cpp.i:
	$(MAKE) -f CMakeFiles/nonlinear_conjugate_gradient.dir/build.make CMakeFiles/nonlinear_conjugate_gradient.dir/src/problem.cpp.i
.PHONY : src/problem.cpp.i

src/problem.s: src/problem.cpp.s

.PHONY : src/problem.s

# target to generate assembly for a file
src/problem.cpp.s:
	$(MAKE) -f CMakeFiles/nonlinear_conjugate_gradient.dir/build.make CMakeFiles/nonlinear_conjugate_gradient.dir/src/problem.cpp.s
.PHONY : src/problem.cpp.s

src/results.o: src/results.cpp.o

.PHONY : src/results.o

# target to build an object file
src/results.cpp.o:
	$(MAKE) -f CMakeFiles/nonlinear_conjugate_gradient.dir/build.make CMakeFiles/nonlinear_conjugate_gradient.dir/src/results.cpp.o
.PHONY : src/results.cpp.o

src/results.i: src/results.cpp.i

.PHONY : src/results.i

# target to preprocess a source file
src/results.cpp.i:
	$(MAKE) -f CMakeFiles/nonlinear_conjugate_gradient.dir/build.make CMakeFiles/nonlinear_conjugate_gradient.dir/src/results.cpp.i
.PHONY : src/results.cpp.i

src/results.s: src/results.cpp.s

.PHONY : src/results.s

# target to generate assembly for a file
src/results.cpp.s:
	$(MAKE) -f CMakeFiles/nonlinear_conjugate_gradient.dir/build.make CMakeFiles/nonlinear_conjugate_gradient.dir/src/results.cpp.s
.PHONY : src/results.cpp.s

tests/eigen_omp_oprod.o: tests/eigen_omp_oprod.cpp.o

.PHONY : tests/eigen_omp_oprod.o

# target to build an object file
tests/eigen_omp_oprod.cpp.o:
	$(MAKE) -f CMakeFiles/nonlinear_conjugate_gradient.dir/build.make CMakeFiles/nonlinear_conjugate_gradient.dir/tests/eigen_omp_oprod.cpp.o
.PHONY : tests/eigen_omp_oprod.cpp.o

tests/eigen_omp_oprod.i: tests/eigen_omp_oprod.cpp.i

.PHONY : tests/eigen_omp_oprod.i

# target to preprocess a source file
tests/eigen_omp_oprod.cpp.i:
	$(MAKE) -f CMakeFiles/nonlinear_conjugate_gradient.dir/build.make CMakeFiles/nonlinear_conjugate_gradient.dir/tests/eigen_omp_oprod.cpp.i
.PHONY : tests/eigen_omp_oprod.cpp.i

tests/eigen_omp_oprod.s: tests/eigen_omp_oprod.cpp.s

.PHONY : tests/eigen_omp_oprod.s

# target to generate assembly for a file
tests/eigen_omp_oprod.cpp.s:
	$(MAKE) -f CMakeFiles/nonlinear_conjugate_gradient.dir/build.make CMakeFiles/nonlinear_conjugate_gradient.dir/tests/eigen_omp_oprod.cpp.s
.PHONY : tests/eigen_omp_oprod.cpp.s

tests/log_reg_random_test.o: tests/log_reg_random_test.cpp.o

.PHONY : tests/log_reg_random_test.o

# target to build an object file
tests/log_reg_random_test.cpp.o:
	$(MAKE) -f CMakeFiles/nonlinear_conjugate_gradient.dir/build.make CMakeFiles/nonlinear_conjugate_gradient.dir/tests/log_reg_random_test.cpp.o
.PHONY : tests/log_reg_random_test.cpp.o

tests/log_reg_random_test.i: tests/log_reg_random_test.cpp.i

.PHONY : tests/log_reg_random_test.i

# target to preprocess a source file
tests/log_reg_random_test.cpp.i:
	$(MAKE) -f CMakeFiles/nonlinear_conjugate_gradient.dir/build.make CMakeFiles/nonlinear_conjugate_gradient.dir/tests/log_reg_random_test.cpp.i
.PHONY : tests/log_reg_random_test.cpp.i

tests/log_reg_random_test.s: tests/log_reg_random_test.cpp.s

.PHONY : tests/log_reg_random_test.s

# target to generate assembly for a file
tests/log_reg_random_test.cpp.s:
	$(MAKE) -f CMakeFiles/nonlinear_conjugate_gradient.dir/build.make CMakeFiles/nonlinear_conjugate_gradient.dir/tests/log_reg_random_test.cpp.s
.PHONY : tests/log_reg_random_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... nonlinear_conjugate_gradient"
	@echo "... src/cg.o"
	@echo "... src/cg.i"
	@echo "... src/cg.s"
	@echo "... src/line_search.o"
	@echo "... src/line_search.i"
	@echo "... src/line_search.s"
	@echo "... src/problem.o"
	@echo "... src/problem.i"
	@echo "... src/problem.s"
	@echo "... src/results.o"
	@echo "... src/results.i"
	@echo "... src/results.s"
	@echo "... tests/eigen_omp_oprod.o"
	@echo "... tests/eigen_omp_oprod.i"
	@echo "... tests/eigen_omp_oprod.s"
	@echo "... tests/log_reg_random_test.o"
	@echo "... tests/log_reg_random_test.i"
	@echo "... tests/log_reg_random_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

