//
// Created by alireza on 04/09/2020.
//
#include "external_libs.h"


#ifndef NONLINEAR_CONJUGATE_GRADIENT_LINE_SEARCH_H
#define NONLINEAR_CONJUGATE_GRADIENT_LINE_SEARCH_H

//scalar



#endif //NONLINEAR_CONJUGATE_GRADIENT_LINE_SEARCH_H
