//
// Created by alireza on 04/09/2020.
//
#include "cg.h"
#ifndef NONLINEAR_CONJUGATE_GRADIENT_METHODS_H
#define NONLINEAR_CONJUGATE_GRADIENT_METHODS_H

#endif //NONLINEAR_CONJUGATE_GRADIENT_METHODS_H
